version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spotlight-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotlight
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotlight-api
    restart: unless-stopped
    ports:
      - "3333:3333"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      HOST: "0.0.0.0"
      PORT: "3333"
      DB_CONNECTION: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_DATABASE: "spotlight"
    command: ["dumb-init", "node", "build/server.js"]
